import {
  Activity,
  BadgeCheck,
  Briefcase,
  CalendarRange,
  CircleHelp,
  ClipboardList,
  Database,
  FileCheck,
  Fingerprint,
  Headphones,
  History,
  Lock,
  Network,
  PenLine,
  ScanSearch,
  ShieldCheck,
  Shuffle,
  Smartphone,
  Stethoscope,
  Timer,
  Workflow,
} from 'lucide-react'

const icons = {
  activity: Activity,
  badgeCheck: BadgeCheck,
  briefcase: Briefcase,
  calendarRange: CalendarRange,
  clipboardList: ClipboardList,
  database: Database,
  fileCheck: FileCheck,
  fingerprint: Fingerprint,
  headphones: Headphones,
  history: History,
  lock: Lock,
  network: Network,
  penLine: PenLine,
  scanSearch: ScanSearch,
  shieldCheck: ShieldCheck,
  shuffle: Shuffle,
  smartphone: Smartphone,
  stethoscope: Stethoscope,
  timer: Timer,
  workflow: Workflow,
}

export function getIcon(name) {
  return icons[name] ?? CircleHelp
}
