import {
  Activity,
  BadgeCheck,
  BarChart3,
  Bell,
  Briefcase,
  CalendarRange,
  CircleHelp,
  ClipboardList,
  Database,
  Download,
  Eye,
  FileCheck,
  FileEdit,
  Fingerprint,
  GitCompare,
  Headphones,
  History,
  Layers,
  ListChecks,
  Lock,
  MapPin,
  Network,
  Package,
  PenLine,
  RefreshCw,
  ScanSearch,
  ShieldCheck,
  Shuffle,
  Smartphone,
  Stethoscope,
  Timer,
  Truck,
  UserCheck,
  Users,
  Workflow,
} from 'lucide-react'

const icons = {
  barChart3: BarChart3,
  bell: Bell,
  eye: Eye,
  gitCompare: GitCompare,
  listChecks: ListChecks,
  package: Package,
  refreshCw: RefreshCw,
  truck: Truck,
  activity: Activity,
  badgeCheck: BadgeCheck,
  briefcase: Briefcase,
  calendarRange: CalendarRange,
  clipboardList: ClipboardList,
  database: Database,
  download: Download,
  fileCheck: FileCheck,
  fileEdit: FileEdit,
  fingerprint: Fingerprint,
  headphones: Headphones,
  history: History,
  layers: Layers,
  lock: Lock,
  mapPin: MapPin,
  network: Network,
  penLine: PenLine,
  scanSearch: ScanSearch,
  shieldCheck: ShieldCheck,
  shuffle: Shuffle,
  smartphone: Smartphone,
  stethoscope: Stethoscope,
  timer: Timer,
  userCheck: UserCheck,
  users: Users,
  workflow: Workflow,
}

export function getIcon(name) {
  return icons[name] ?? CircleHelp
}
